### ISSUE TITLE
Explain about screenshots

### ISSUE THREAD

**Issue by LuismiInTheZone** [CTF-handbooks/map-maker-handbook#3]
Tell that you need to convert an image to 750x500 and 2:3… I could do a PR, but since I’m doing this with a phone, is a bit hard, I’ll do it if not this afternoon (for me) with the computer

**Comment by a-blob** [comment]
I haven't got to that part yet so that isn't written. After all, this is a work in progress. But of course, feel free to create PRs to improve/add things.
